SELECT CUST_NUM, COMPANY, CREDIT_LIMIT, ORDER_NUM, AMOUNT
FROM customers, ORDERS
WHERE CREDIT_LIMIT > 0.00 AND AMOUNT > 0.00 AND AMOUNT < CREDIT_LIMIT AND (CREDIT_LIMIT - AMOUNT) < = 5000.00 AND CUST_NUM = CUST;
