SELECT PRODUCT_ID, MFR_ID, DESCRIPTION, CUST_NUM, COMPANY, ORDER_NUM, ORDER_DATE
FROM PRODUCTS, customers, ORDERS
WHERE cust = CUST_NUM AND product = PRODUCT_ID AND mfr = MFR_ID AND amount < 1000.00
ORDER BY ORDER_DATE;
